version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    # environment:
    #   - BASE_URL=http://moa
    depends_on:
      - redis
    networks:
      - app_network
    ports:
      - "1000:1000"

  redis:
    image: redis:alpine
    container_name: redis_db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - app_network
    ports:
      - "80:80"

networks:
  app_network:
    driver: bridge
